name = "vue-ssr-poc"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm run build:prod"

[build.upload]
format = "modules"
main = "./dist/index.mjs"